name: expensetracker
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  go_router: ^14.8.1
  fpdart: ^1.1.1
  flutter_screenutil: ^5.9.3
  sqflite: ^2.4.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/OFL.txt
    - assets/fonts/Poppins-Black.ttf
    - assets/fonts/Poppins-BlackItalic.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-BoldItalic.ttf
    - assets/fonts/Poppins-ExtraBold.ttf
    - assets/fonts/Poppins-ExtraBoldItalic.ttf
    - assets/fonts/Poppins-ExtraLight.ttf
    - assets/fonts/Poppins-ExtraLightItalic.ttf
    - assets/fonts/Poppins-Italic.ttf
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-LightItalic.ttf
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-MediumItalic.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-SemiBold.ttf
    - assets/fonts/Poppins-SemiBoldItalic.ttf
    - assets/fonts/Poppins-Thin.ttf
    - assets/fonts/Poppins-ThinItalic.ttf

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
